Description: >
    Runs the Jenkins docker image

Parameters: 

    VPC:
        Description: The VPC that the ECS cluster is deployed to
        Type: AWS::EC2::VPC::Id
        
    Cluster:
        Description: Please provide the ECS Cluster ID that this service should run on
        Type: String

    DesiredCount:
        Description: How many instances of this task should we run across our cluster?
        Type: Number
        Default: 1

    LoadBalancer:
        Description: The Application Load Balancer to register with
        Type: String

    DockerImage:
        Description: The docker image to use for Jenkins
        Type: String
        Default: jenkins/jenkins:lts
        
Resources:

    Service:
        Type: AWS::ECS::Service
        DependsOn: !Ref LoadBalancer
        Properties:
            Cluster: !Ref Cluster
            Role: !Ref ServiceRole
            HealthCheckGracePeriodSeconds: 30
            DesiredCount: !Ref DesiredCount
            TaskDefinition: !Ref TaskDefinition
            PlacementStrategies:
                - Type: spread
                  Field: host
            LoadBalancers:
                - ContainerName: 'jenkins-master'
                  ContainerPort: '8080'
                  LoadBalancerName: !Ref LoadBalancer

    TaskDefinition:
        Type: 'AWS::ECS::TaskDefinition'
        Properties:
            Family: jenkins-master
            NetworkMode: bridge
            Volumes:
                -
                    Host:
                        SourcePath: /var/jenkins_home
                    Name: jenkins_home
            ContainerDefinitions:
                - Name: jenkins-master
                  MountPoints:
                      - SourceVolume: jenkins_home
                        ContainerPath: /var/jenkins_home                  
                  Essential: true
                  Image: !Ref DockerImage
                  Cpu: 1024
                  MemoryReservation: 1984
                  PortMappings:
                      - ContainerPort: 8080
                        HostPort: 8080                        
                        Protocol: tcp
                      - ContainerPort: 50000
                        HostPort: 50000
                        Protocol: tcp
                  LogConfiguration:
                      LogDriver: awslogs
                      Options:
                          awslogs-group: !Ref AWS::StackName
                          awslogs-region: !Ref AWS::Region
                          awslogs-stream-prefix: jenkins
                  Environment:
                      - Name: JAVA_OPTS
                        Value: -Duser.timezone=Australia/Sydney

   
    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 365  

  

    # This IAM Role grants the service access to register/unregister with the 
    # Application Load Balancer (ALB). It is based on the default documented here:
    # http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_IAM_role.html
    ServiceRole:
        Type: 'AWS::IAM::Role'
        Description: "Jenkins master ECS Service Role"
        Properties:
            RoleName: !Sub ecs-service-${AWS::StackName}
            Path: /
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - ecs.amazonaws.com
                      Action:
                          - 'sts:AssumeRole'
            Policies:
                - PolicyName: ecs-service
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                                - 'ec2:AuthorizeSecurityGroupIngress'
                                - 'ec2:Describe*'
                                - 'elasticloadbalancing:DeregisterInstancesFromLoadBalancer'
                                - 'elasticloadbalancing:Describe*'
                                - 'elasticloadbalancing:RegisterInstancesWithLoadBalancer'
                                - 'elasticloadbalancing:DeregisterTargets'
                                - 'elasticloadbalancing:RegisterTargets'
                            Resource: '*'